is:
  - headers.acceptJson
  - headers.testScenarioHeader
  - errors.formatNino
  - errors.formatTaxYear
  - errors.formatBenefitId
  - errors.ruleTaxYearRangeInvalid
  - errors.ruleTaxYearNotSupported
  - errors.ruleTaxYearNotEnded
  - errors.ruleIgnoreForbidden
  - errors.clientOrAgentNotAuthorised
  - errors.notFound
displayName: Ignore State Benefit
description: 'This endpoint enables you to mark a state benefit as ignored. Customer-added benefits can’t be ignored, only deleted. A National Insurance number, tax year and benefit ID must be provided.'
(annotations.sandboxData): !include ../scenarios/ignoreBenefit.md
(annotations.scope): "write:self-assessment"
securedBy: [ sec.oauth_2_0: { scopes: [ "write:self-assessment" ] } ]
responses:
  200:
    body:
      application/json:
        type: !include ../schemas/ignore_response.json
        example: !include ../examples/ignoreBenefit/response.json
    headers:
      X-CorrelationId:
        example: a1e8057e-fbbc-47a8-a8b4-78d9f015c253
        description: Unique ID for operation tracking <br> String, 36 characters.